services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file: .env
    command: node ./dist/server/entry.mjs
    ports:
      - "4321"
    networks:
      - qntnio
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qntnio.rule=Host(`qntn.io`)"
      - "traefik.http.routers.qntnio.entrypoints=websecure"
      - "traefik.http.routers.qntnio.tls.certresolver=letsencrypt"

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - qntnio
    volumes:
      - redis_data:/data

networks:
  qntnio:
  traefik:
    external: true

volumes:
  redis_data:
