services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file: .env
    command: node ./dist/server/entry.mjs
    ports:
      - "4321"
    networks:
      - qntnio
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qntnio.rule=Host(`qntn.io`) || Host(`quintencoret.nl`)"
      - "traefik.http.routers.qntnio.entrypoints=websecure"
      - "traefik.http.routers.qntnio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.note.middlewares=myratelimit@file,mycompress@file,myhsts@file,mysecurityheaders@file"

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - qntnio
    volumes:
      - redis_data:/data

networks:
  qntnio:
  traefik:
    external: true

volumes:
  redis_data:
